function [V,Vice,O,Oice,ZWT,OF,OS,OH,OL,Psi_s_H,Psi_s_L,Rd,Qi_out,WTR, Rh,Lk,f,WIS,Ts,Pr_sno,Pr_liq,Csno,Cice,NDVI,rb_H,rb_L,rs_sunH, rs_sunL,rs_shdH,rs_shdL,r_litter, An_L,An_H,Rdark_L,Rdark_H,Ci_sunH,Ci_sunL,Ci_shdH,Ci_shdL, rap_H,rap_L,r_soil,b_soil,alp_soil,ra,Rn, H,QE,Qv,Lpho,T_H,T_L,EIn_H,EIn_L,EG,ESN,ESN_In,ELitter,EWAT,EICE,EIn_urb,EIn_rock,dw_SNO, G,Gfin,Tdp,Tdpsnow,Tdeb,Tdamp,Tice,Tdp_H,Tdp_L,SWE,SND,ros,In_SWE,SP_wc,WR_SP,U_SWE,NIn_SWE,dQ,Qfm,t_sls,DQ,DT, WAT,ICE,ICE_D,IP_wc,WR_IP,NIce,Cicew,Csnow,FROCK,Imelt,Smelt, In_H,In_L,In_Litter,In_urb,In_rock,Dr_H,Dr_L,SE_rock,SE_urb,Lk_wat,Lk_rock,er, gsr_H,Psi_x_H,Psi_l_H,Jsx_H,Jxl_H,Kleaf_H,Kx_H,Vx_H,Vl_H, gsr_L,Psi_x_L,Psi_l_L,Jsx_L,Jxl_L,Kleaf_L,Kx_L,Vx_L,Vl_L, fapar_H,fapar_L,SIF_H,SIF_L, snow_alb,tau_sno,e_sno,Ws_under,dQVEG,HV,QEV,TsV,Ts_under,EK,POT] = HYDROLOGIC_UNIT(Vtm1,Oicetm1,aR,Zs, EvL_Zs,Inf_Zs,Zinf,RfH_Zs,RfL_Zs,dz,Dz,ms,Kbot,Pr,Ta,Ds,Ws,zatm,Tstm1,Tstm1_under,IrD,dt,dth,ea,N,Pre,Tstm0, LAI_H,SAI_H,LAI_L,SAI_L,LAIdead_H,LAIdead_L,Rrootl_H,Rrootl_L,BLit,Sllit,Kct, Datam,DeltaGMT,Lon,Lat,t_bef,t_aft, Ccrown,Cbare,Crock,Curb,Cwat, Soil_Param,Interc_Param,SnowIce_Param,VegH_Param,VegL_Param, Zs_deb,Deb_Par, ZR95_H,ZR95_L, SAB1,SAB2,SAD1,SAD2,PARB,PARD,SvF,SNDtm1,snow_albtm1,Color_Class,OM_H,OM_L, PFT_opt_H,PFT_opt_L,hc_H,hc_L,d_leaf_H,d_leaf_L, Ca,Oa,Citm1_sunH,Citm1_shdH,Citm1_sunL,Citm1_shdL, e_rel_H,e_relN_H,e_rel_L,e_relN_L, e_snotm1,In_Htm1,In_Ltm1,In_Littertm1,In_urbtm1,In_rocktm1,SWEtm1,In_SWEtm1, Tdebtm1,Tdptm1,Tdpsnowtm1,Tdamptm1,Ticetm1, WATtm1,ICEtm1,IP_wctm1,ICE_Dtm1,Cicewtm1, Vxtm1_H,Vltm1_H,Vxtm1_L,Vltm1_L,Psi_xtm1_H,Psi_ltm1_H,Psi_xtm1_L,Psi_ltm1_L, FROCKtm1,Krock,Ws_undertm1, Tdew,t_slstm1,rostm1,SP_wctm1,fpr,Pr_sno_day, Urb_Par,In_max_urb,In_max_rock,K_usle,tau_snotm1,Ta_day,Slo_top,Slo_pot,Asur,Ared,aTop,EKtm1,q_runon,Qi_in, pow_dis,a_dis,Salt, SPAR,SN,OPT_min_SPD,OPT_VegSnow,OPT_SoilTemp,OPT_PlantHydr,Opt_CR,Opt_ST,Opt_ST2,OPT_SM,OPT_STh,OPT_FR_SOIL,OPT_PH)
% Wrapper for logging I/O to tc.HYDROLOGIC_UNIT
    w = whos;
    inputs = struct();
    for a = 1:length(w)
        inputs.(w(a).name) = eval(w(a).name);
    end
    log_inputs('HYDROLOGIC_UNIT', inputs);

    [V,Vice,O,Oice,ZWT,OF,OS,OH,OL,Psi_s_H,Psi_s_L,Rd,Qi_out,WTR, Rh,Lk,f,WIS,Ts,Pr_sno,Pr_liq,Csno,Cice,NDVI,rb_H,rb_L,rs_sunH, rs_sunL,rs_shdH,rs_shdL,r_litter, An_L,An_H,Rdark_L,Rdark_H,Ci_sunH,Ci_sunL,Ci_shdH,Ci_shdL, rap_H,rap_L,r_soil,b_soil,alp_soil,ra,Rn, H,QE,Qv,Lpho,T_H,T_L,EIn_H,EIn_L,EG,ESN,ESN_In,ELitter,EWAT,EICE,EIn_urb,EIn_rock,dw_SNO, G,Gfin,Tdp,Tdpsnow,Tdeb,Tdamp,Tice,Tdp_H,Tdp_L,SWE,SND,ros,In_SWE,SP_wc,WR_SP,U_SWE,NIn_SWE,dQ,Qfm,t_sls,DQ,DT, WAT,ICE,ICE_D,IP_wc,WR_IP,NIce,Cicew,Csnow,FROCK,Imelt,Smelt, In_H,In_L,In_Litter,In_urb,In_rock,Dr_H,Dr_L,SE_rock,SE_urb,Lk_wat,Lk_rock,er, gsr_H,Psi_x_H,Psi_l_H,Jsx_H,Jxl_H,Kleaf_H,Kx_H,Vx_H,Vl_H, gsr_L,Psi_x_L,Psi_l_L,Jsx_L,Jxl_L,Kleaf_L,Kx_L,Vx_L,Vl_L, fapar_H,fapar_L,SIF_H,SIF_L, snow_alb,tau_sno,e_sno,Ws_under,dQVEG,HV,QEV,TsV,Ts_under,EK,POT] = tc.HYDROLOGIC_UNIT(Vtm1,Oicetm1,aR,Zs, EvL_Zs,Inf_Zs,Zinf,RfH_Zs,RfL_Zs,dz,Dz,ms,Kbot,Pr,Ta,Ds,Ws,zatm,Tstm1,Tstm1_under,IrD,dt,dth,ea,N,Pre,Tstm0, LAI_H,SAI_H,LAI_L,SAI_L,LAIdead_H,LAIdead_L,Rrootl_H,Rrootl_L,BLit,Sllit,Kct, Datam,DeltaGMT,Lon,Lat,t_bef,t_aft, Ccrown,Cbare,Crock,Curb,Cwat, Soil_Param,Interc_Param,SnowIce_Param,VegH_Param,VegL_Param, Zs_deb,Deb_Par, ZR95_H,ZR95_L, SAB1,SAB2,SAD1,SAD2,PARB,PARD,SvF,SNDtm1,snow_albtm1,Color_Class,OM_H,OM_L, PFT_opt_H,PFT_opt_L,hc_H,hc_L,d_leaf_H,d_leaf_L, Ca,Oa,Citm1_sunH,Citm1_shdH,Citm1_sunL,Citm1_shdL, e_rel_H,e_relN_H,e_rel_L,e_relN_L, e_snotm1,In_Htm1,In_Ltm1,In_Littertm1,In_urbtm1,In_rocktm1,SWEtm1,In_SWEtm1, Tdebtm1,Tdptm1,Tdpsnowtm1,Tdamptm1,Ticetm1, WATtm1,ICEtm1,IP_wctm1,ICE_Dtm1,Cicewtm1, Vxtm1_H,Vltm1_H,Vxtm1_L,Vltm1_L,Psi_xtm1_H,Psi_ltm1_H,Psi_xtm1_L,Psi_ltm1_L, FROCKtm1,Krock,Ws_undertm1, Tdew,t_slstm1,rostm1,SP_wctm1,fpr,Pr_sno_day, Urb_Par,In_max_urb,In_max_rock,K_usle,tau_snotm1,Ta_day,Slo_top,Slo_pot,Asur,Ared,aTop,EKtm1,q_runon,Qi_in, pow_dis,a_dis,Salt, SPAR,SN,OPT_min_SPD,OPT_VegSnow,OPT_SoilTemp,OPT_PlantHydr,Opt_CR,Opt_ST,Opt_ST2,OPT_SM,OPT_STh,OPT_FR_SOIL,OPT_PH);
    
    w = whos;
    outputs = struct();
    for a = 1:length(w)
        outputs.(w(a).name) = eval(w(a).name);
    end
    log_outputs('HYDROLOGIC_UNIT', outputs);
end
