function [Ts,Pr_sno,Pr_liq,Ws_under,Csno,Cice,Cfol_H,Cfol_L,CLitter,NDVI,rb_H,rb_L,rs_sunH,rs_sunL,rs_shdH,rs_shdL,r_litter, An_L,An_H,Rdark_L,Rdark_H,Ci_sunH,Ci_sunL,Ci_shdH,Ci_shdL,rap_H,rap_L,ra,Rn, H,QE,Qv,Lpho,T_H,T_L,EIn_H,EIn_L,EG,ESN,ESN_In,EWAT,EICE,ELitter,EIn_urb,EIn_rock,dw_SNO, G,Gfin,Tdp,Tdpsnow,O,Oice,Tdamp,Tdeb,Tice,SWE,SND,ros,In_SWE,SP_wc,WR_SP,U_SWE,NIn_SWE,dQ,Qfm,t_sls,DQ,DT, In_H,In_L,In_Litter,In_urb,In_rock,Dr_H,Dr_L,SE_rock,SE_urb,WIS, ICE,ICE_D,IP_wc,WR_IP,NIce,Cicew,Csnow, snow_alb,tau_sno,e_sno, fapar_H,fapar_L,SIF_H,SIF_L, gsr_H,Psi_x_H,Psi_l_H,Jsx_H,Jxl_H,Kleaf_H,Kx_H,Vx_H,Vl_H, gsr_L,Psi_x_L,Psi_l_L,Jsx_L,Jxl_L,Kleaf_L,Kx_L,Vx_L,Vl_L, dQVEG,HV,QEV,TsV,Ts_under,WAT,q_run,EG_dis,J_Hdis,J_Ldis,Imelt,Smelt] = SVAT_UNIT(Tstm0,Pr,Ta,Ds,Ws,zatm,Tstm1,Tstm1_under,dt,ea,Latm,N,Pre, OS,Psi_s_H,Psi_s_L,gsr_H,gsr_L,Exwat_H,Exwat_L, LAI_H,SAI_H,LAI_L,SAI_L,LAIdead_H,LAIdead_L,BLit,Sllit,Kct,TminS,TmaxS, Sp_SN_In,Sp_LAI_L_In,Sp_LAI_H_In,h_S, Ccrown,Cbare,Crock,Curb,Cwat,ydepth,Ccrown_L, Rsw,PAR,SvF,SNDtm1,snow_albtm1,Color_Class,OM_H,OM_L, PFT_opt_H,PFT_opt_L,hc_H,hc_L,d_leaf_H,d_leaf_L, r_soil,b_soil,alp_soil,gcI,KcI, KnitH,KnitL,mSl_H,Sl_H,mSl_L,Sl_L,Ca,Oa,Citm1_sunH,Citm1_shdH,CT_H,Citm1_sunL,Citm1_shdL,CT_L,Vmax_H,Vmax_L,FI_H,FI_L,a1_H,go_H,a1_L,go_L, DSE_H,Ha_H,Do_H,e_rel_H,e_relN_H,DSE_L,Ha_L,Do_L,e_rel_L,e_relN_L,gmes_H,rjv_H,gmes_L,rjv_L, e_snotm1,In_Htm1,In_Ltm1,In_Littertm1,In_urbtm1,In_rocktm1,SWEtm1,In_SWEtm1, Oicetm1,Otm1,Tdptm1,Tdpsnowtm1,Tdamptm1,Ticetm1,dz,Zs,ms,rsd,lan_dry,lan_s,cv_s,SPAR,L,Pe,O33,alpVG,nVG,Phy,s_SVG,bVG,Osat,Ohy,CTt, lan_oth,cv_oth,CTt_oth,Zs_deb,Deb_Par,Tdebtm1, Tdew,t_slstm1,rostm1,SP_wctm1,fpr,WatFreez_Th,dz_ice, Pr_sno_day,Th_Pr_sno,ros_max1,ros_max2, Urb_Par,In_max_urb,In_max_rock,tau_snotm1,Ta_day,Ws_undertm1, EvL_Zs,RfH_Zs,RfL_Zs,Vtm1,WATtm1, ICEtm1,IP_wctm1,ICE_Dtm1,Ice_wc_sp,ros_Ice_thr,Aice,Cicewtm1, Vxtm1_H,Vltm1_H,Vxtm1_L,Vltm1_L,Psi_xtm1_H,Psi_ltm1_H,Psi_xtm1_L,Psi_ltm1_L, Psi_sto_50_H,Psi_sto_00_H,ZR95_H, Psi_sto_50_L,Psi_sto_00_L,ZR95_L, Axyl_H,PsiL50_H,PsiL00_H,Kleaf_max_H,Cl_H,Kx_max_H,PsiX50_H,Cx_H, Axyl_L,PsiL50_L,PsiL00_L,Kleaf_max_L,Cl_L,Kx_max_L,PsiX50_L,Cx_L, min_SPD,OPT_VegSnow,OPT_SoilTemp,OPT_PlantHydr,Opt_CR,Opt_ST,Opt_ST2,OPT_STh,OPT_FR_SOIL,OPT_PH)
% Wrapper for logging I/O to tc.SVAT_UNIT
    global id_location;
    w = whos;
    inputs = struct();
    for a = 1:length(w)
        inputs.(w(a).name) = eval(w(a).name);
    end
    log_inputs(id_location, 'SVAT_UNIT', inputs);

    [Ts,Pr_sno,Pr_liq,Ws_under,Csno,Cice,Cfol_H,Cfol_L,CLitter,NDVI,rb_H,rb_L,rs_sunH,rs_sunL,rs_shdH,rs_shdL,r_litter, An_L,An_H,Rdark_L,Rdark_H,Ci_sunH,Ci_sunL,Ci_shdH,Ci_shdL,rap_H,rap_L,ra,Rn, H,QE,Qv,Lpho,T_H,T_L,EIn_H,EIn_L,EG,ESN,ESN_In,EWAT,EICE,ELitter,EIn_urb,EIn_rock,dw_SNO, G,Gfin,Tdp,Tdpsnow,O,Oice,Tdamp,Tdeb,Tice,SWE,SND,ros,In_SWE,SP_wc,WR_SP,U_SWE,NIn_SWE,dQ,Qfm,t_sls,DQ,DT, In_H,In_L,In_Litter,In_urb,In_rock,Dr_H,Dr_L,SE_rock,SE_urb,WIS, ICE,ICE_D,IP_wc,WR_IP,NIce,Cicew,Csnow, snow_alb,tau_sno,e_sno, fapar_H,fapar_L,SIF_H,SIF_L, gsr_H,Psi_x_H,Psi_l_H,Jsx_H,Jxl_H,Kleaf_H,Kx_H,Vx_H,Vl_H, gsr_L,Psi_x_L,Psi_l_L,Jsx_L,Jxl_L,Kleaf_L,Kx_L,Vx_L,Vl_L, dQVEG,HV,QEV,TsV,Ts_under,WAT,q_run,EG_dis,J_Hdis,J_Ldis,Imelt,Smelt] = tc.SVAT_UNIT(Tstm0,Pr,Ta,Ds,Ws,zatm,Tstm1,Tstm1_under,dt,ea,Latm,N,Pre, OS,Psi_s_H,Psi_s_L,gsr_H,gsr_L,Exwat_H,Exwat_L, LAI_H,SAI_H,LAI_L,SAI_L,LAIdead_H,LAIdead_L,BLit,Sllit,Kct,TminS,TmaxS, Sp_SN_In,Sp_LAI_L_In,Sp_LAI_H_In,h_S, Ccrown,Cbare,Crock,Curb,Cwat,ydepth,Ccrown_L, Rsw,PAR,SvF,SNDtm1,snow_albtm1,Color_Class,OM_H,OM_L, PFT_opt_H,PFT_opt_L,hc_H,hc_L,d_leaf_H,d_leaf_L, r_soil,b_soil,alp_soil,gcI,KcI, KnitH,KnitL,mSl_H,Sl_H,mSl_L,Sl_L,Ca,Oa,Citm1_sunH,Citm1_shdH,CT_H,Citm1_sunL,Citm1_shdL,CT_L,Vmax_H,Vmax_L,FI_H,FI_L,a1_H,go_H,a1_L,go_L, DSE_H,Ha_H,Do_H,e_rel_H,e_relN_H,DSE_L,Ha_L,Do_L,e_rel_L,e_relN_L,gmes_H,rjv_H,gmes_L,rjv_L, e_snotm1,In_Htm1,In_Ltm1,In_Littertm1,In_urbtm1,In_rocktm1,SWEtm1,In_SWEtm1, Oicetm1,Otm1,Tdptm1,Tdpsnowtm1,Tdamptm1,Ticetm1,dz,Zs,ms,rsd,lan_dry,lan_s,cv_s,SPAR,L,Pe,O33,alpVG,nVG,Phy,s_SVG,bVG,Osat,Ohy,CTt, lan_oth,cv_oth,CTt_oth,Zs_deb,Deb_Par,Tdebtm1, Tdew,t_slstm1,rostm1,SP_wctm1,fpr,WatFreez_Th,dz_ice, Pr_sno_day,Th_Pr_sno,ros_max1,ros_max2, Urb_Par,In_max_urb,In_max_rock,tau_snotm1,Ta_day,Ws_undertm1, EvL_Zs,RfH_Zs,RfL_Zs,Vtm1,WATtm1, ICEtm1,IP_wctm1,ICE_Dtm1,Ice_wc_sp,ros_Ice_thr,Aice,Cicewtm1, Vxtm1_H,Vltm1_H,Vxtm1_L,Vltm1_L,Psi_xtm1_H,Psi_ltm1_H,Psi_xtm1_L,Psi_ltm1_L, Psi_sto_50_H,Psi_sto_00_H,ZR95_H, Psi_sto_50_L,Psi_sto_00_L,ZR95_L, Axyl_H,PsiL50_H,PsiL00_H,Kleaf_max_H,Cl_H,Kx_max_H,PsiX50_H,Cx_H, Axyl_L,PsiL50_L,PsiL00_L,Kleaf_max_L,Cl_L,Kx_max_L,PsiX50_L,Cx_L, min_SPD,OPT_VegSnow,OPT_SoilTemp,OPT_PlantHydr,Opt_CR,Opt_ST,Opt_ST2,OPT_STh,OPT_FR_SOIL,OPT_PH);
    
    w = whos;
    outputs = struct();
    for a = 1:length(w)
        outputs.(w(a).name) = eval(w(a).name);
    end
    log_outputs(id_location, 'SVAT_UNIT', outputs);
end
