function [LAI_H,B_H,NPP_H,ANPP_H,Rg_H,RA_H,Rms_H,Rmr_H,Rmc_H,PHE_S_H, dflo_H,AgeL_H,e_rel_H,e_relN_H, LAI_L,B_L,NPP_L,ANPP_L,Rg_L,RA_L,Rms_L,Rmr_L,Rmc_L,PHE_S_L, dflo_L,AgeL_L,e_rel_L,e_relN_L, SAI_H,hc_H,SAI_L,hc_L, LAIdead_H,NBLeaf_H,Sr_H,Slf_H,Sfr_H,Sll_H,Swm_H,Rexmy_H,NupI_H,NuLit_H, LAIdead_L,NBLeaf_L,Sr_L,Slf_L,Sfr_L,Sll_L,Swm_L,Rexmy_L,NupI_L,NuLit_L, Rrootl_H,AgeDL_H,Bfac_dayH,Bfac_weekH,NPPI_H,TdpI_H,PARI_H,NBLI_H,RB_H,FNC_H,Nreserve_H,Preserve_H,Kreserve_H,rNc_H,rPc_H,rKc_H,ManIH, Rrootl_L,AgeDL_L,Bfac_dayL,Bfac_weekL,NPPI_L,TdpI_L,PARI_L,NBLI_L,RB_L,FNC_L,Nreserve_L,Preserve_L,Kreserve_L,rNc_L,rPc_L,rKc_L,ManIL, TexC_H,TexN_H,TexP_H,TexK_H,TNIT_H,TPHO_H,TPOT_H,SupN_H,SupP_H,SupK_H,ISOIL_H, TexC_L,TexN_L,TexP_L,TexK_L,TNIT_L,TPHO_L,TPOT_L,SupN_L,SupP_L,SupK_L,ISOIL_L, BA_H,Tden_H,AgePl_H,BA_L,Tden_L,AgePl_L,Ccrown_t] = VEGETATION_MODULE_PAR(cc_max,Ccrown,ZR_H,ZR_L,B_Htm1, PHE_S_Htm1,dflo_Htm1,AgeL_Htm1,AgeDL_Htm1, Ta24,PAR24,Tdp_H24,Psi_x_H24,Psi_l_H24,An_H24,Rdark_H24,NPP_Htm1,jDay,Datam, NPPI_Htm1,TdpI_Htm1,Bfac_weekHtm1, Stoich_H,aSE_H,VegH_Param_Dyn, Nreserve_Htm1,Preserve_Htm1,Kreserve_Htm1,Nuptake_H,Puptake_H,Kuptake_H,FNC_Htm1,Tden_Htm1,AgePl_Htm1, fab_H,fbe_H,ParEx_H,Mpar_H,TBio_H,SAI_Htm1,hc_Htm1, B_Ltm1,PHE_S_Ltm1,dflo_Ltm1,AgeL_Ltm1,AgeDL_Ltm1, Tdp_L24,Psi_x_L24,Psi_l_L24,An_L24,Rdark_L24,NPP_Ltm1, NPPI_Ltm1,TdpI_Ltm1,Bfac_weekLtm1, NupI_Htm1,NupI_Ltm1,NuLit_Htm1,NuLit_Ltm1,NBLeaf_Htm1,NBLeaf_Ltm1, PARI_Htm1,NBLI_Htm1,PARI_Ltm1,NBLI_Ltm1, Stoich_L,aSE_L,VegL_Param_Dyn, NavlI,Bam,Bem,Ccrown_t_tm1, Nreserve_Ltm1,Preserve_Ltm1,Kreserve_Ltm1,Nuptake_L,Puptake_L,Kuptake_L,FNC_Ltm1,Tden_Ltm1,AgePl_Ltm1, fab_L,fbe_L,ParEx_L,Mpar_L,TBio_L,SAI_Ltm1,hc_Ltm1, ExEM,Lmax_day,L_day,Se_bio,Tdp_bio,OPT_EnvLimitGrowth,OPT_VD,OPT_VCA,OPT_ALLOME,OPT_SoilBiogeochemistry)
% Wrapper for logging I/O to tc.VEGETATION_MODULE_PAR
    global id_location;
    w = whos;
    inputs = struct();
    for a = 1:length(w)
        inputs.(w(a).name) = eval(w(a).name);
    end
    log_inputs(id_location, 'VEGETATION_MODULE_PAR', inputs);

    [LAI_H,B_H,NPP_H,ANPP_H,Rg_H,RA_H,Rms_H,Rmr_H,Rmc_H,PHE_S_H, dflo_H,AgeL_H,e_rel_H,e_relN_H, LAI_L,B_L,NPP_L,ANPP_L,Rg_L,RA_L,Rms_L,Rmr_L,Rmc_L,PHE_S_L, dflo_L,AgeL_L,e_rel_L,e_relN_L, SAI_H,hc_H,SAI_L,hc_L, LAIdead_H,NBLeaf_H,Sr_H,Slf_H,Sfr_H,Sll_H,Swm_H,Rexmy_H,NupI_H,NuLit_H, LAIdead_L,NBLeaf_L,Sr_L,Slf_L,Sfr_L,Sll_L,Swm_L,Rexmy_L,NupI_L,NuLit_L, Rrootl_H,AgeDL_H,Bfac_dayH,Bfac_weekH,NPPI_H,TdpI_H,PARI_H,NBLI_H,RB_H,FNC_H,Nreserve_H,Preserve_H,Kreserve_H,rNc_H,rPc_H,rKc_H,ManIH, Rrootl_L,AgeDL_L,Bfac_dayL,Bfac_weekL,NPPI_L,TdpI_L,PARI_L,NBLI_L,RB_L,FNC_L,Nreserve_L,Preserve_L,Kreserve_L,rNc_L,rPc_L,rKc_L,ManIL, TexC_H,TexN_H,TexP_H,TexK_H,TNIT_H,TPHO_H,TPOT_H,SupN_H,SupP_H,SupK_H,ISOIL_H, TexC_L,TexN_L,TexP_L,TexK_L,TNIT_L,TPHO_L,TPOT_L,SupN_L,SupP_L,SupK_L,ISOIL_L, BA_H,Tden_H,AgePl_H,BA_L,Tden_L,AgePl_L,Ccrown_t] = tc.VEGETATION_MODULE_PAR(cc_max,Ccrown,ZR_H,ZR_L,B_Htm1, PHE_S_Htm1,dflo_Htm1,AgeL_Htm1,AgeDL_Htm1, Ta24,PAR24,Tdp_H24,Psi_x_H24,Psi_l_H24,An_H24,Rdark_H24,NPP_Htm1,jDay,Datam, NPPI_Htm1,TdpI_Htm1,Bfac_weekHtm1, Stoich_H,aSE_H,VegH_Param_Dyn, Nreserve_Htm1,Preserve_Htm1,Kreserve_Htm1,Nuptake_H,Puptake_H,Kuptake_H,FNC_Htm1,Tden_Htm1,AgePl_Htm1, fab_H,fbe_H,ParEx_H,Mpar_H,TBio_H,SAI_Htm1,hc_Htm1, B_Ltm1,PHE_S_Ltm1,dflo_Ltm1,AgeL_Ltm1,AgeDL_Ltm1, Tdp_L24,Psi_x_L24,Psi_l_L24,An_L24,Rdark_L24,NPP_Ltm1, NPPI_Ltm1,TdpI_Ltm1,Bfac_weekLtm1, NupI_Htm1,NupI_Ltm1,NuLit_Htm1,NuLit_Ltm1,NBLeaf_Htm1,NBLeaf_Ltm1, PARI_Htm1,NBLI_Htm1,PARI_Ltm1,NBLI_Ltm1, Stoich_L,aSE_L,VegL_Param_Dyn, NavlI,Bam,Bem,Ccrown_t_tm1, Nreserve_Ltm1,Preserve_Ltm1,Kreserve_Ltm1,Nuptake_L,Puptake_L,Kuptake_L,FNC_Ltm1,Tden_Ltm1,AgePl_Ltm1, fab_L,fbe_L,ParEx_L,Mpar_L,TBio_L,SAI_Ltm1,hc_Ltm1, ExEM,Lmax_day,L_day,Se_bio,Tdp_bio,OPT_EnvLimitGrowth,OPT_VD,OPT_VCA,OPT_ALLOME,OPT_SoilBiogeochemistry);
    
    w = whos;
    outputs = struct();
    for a = 1:length(w)
        outputs.(w(a).name) = eval(w(a).name);
    end
    log_outputs(id_location, 'VEGETATION_MODULE_PAR', outputs);
end
